-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.movies
(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    release_date date NOT NULL,
    description VARCHAR(400) NOT NULL UNIQUE,
    genre VARCHAR(20) NOT NULL,
    runtime VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS public.crew_member
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    job_title VARCHAR(20) NOT NULL,
    picture VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS public.movies_crew_member
(
    id SERIAL PRIMARY KEY,
    movies_id bigserial NOT NULL,
    crew_id bigserial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rating
(
    id SERIAL PRIMARY KEY,
    rate INTEGER NOT NULL,
    title VARCHAR(30),
    comment VARCHAR(200),
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    login VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(75) NOT NULL,
    is_admin boolean NOT NULL
);

ALTER TABLE IF EXISTS public.movies_crew_member
    ADD FOREIGN KEY (movies_id)
    REFERENCES public.movies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.movies_crew_member
    ADD FOREIGN KEY (crew_id)
    REFERENCES public.crew_member (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rating
    ADD CONSTRAINT movie_id FOREIGN KEY (movie_id)
    REFERENCES public.movies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rating
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
