BEGIN;

CREATE TABLE IF NOT EXISTS movies
(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    release_date DATE NOT NULL,
    description VARCHAR(400) NOT NULL UNIQUE,
    genre VARCHAR(20) NOT NULL,
    runtime VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS crew_members
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    job_title VARCHAR(20) NOT NULL,
    picture VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS movies_crew_members
(
    id SERIAL PRIMARY KEY,
    movies_id BIGINT NOT NULL,
    crew_id BIGINT NOT NULL,
    FOREIGN KEY (movies_id) REFERENCES movies (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (crew_id) REFERENCES crew_members (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    login VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(75) NOT NULL,
    is_admin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS ratings
(
    id SERIAL PRIMARY KEY,
    rate INTEGER NOT NULL,
    comment VARCHAR(200),
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (movie_id) REFERENCES movies (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

END;
